name: DEPLOY
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AZCN_SHH_02_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.AZCN_SHH_02_IP }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz ./ root@$${{ secrets.AZCN_SHH_02_IP }}:${{ secrets.WEB_PATH }}
