name: DEPLOY
on:
  push:
    branches:
    - master
   workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ${{ secrets.WEB_PATH }}
        remote_host: ${{ secrets.AZCN_SHH_02_IP }}
        remote_user: root
        remote_key: ${{ secrets.AZCN_SHH_02_SSH_KEY }}
